//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.530
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.1.
// 
namespace ClassLibraryVkontakteChecker.XmlData
{
	using System.Xml.Serialization;

	public class audio_getCount
	{

		/// <summary>
		/// Класс, содержащий в себе audio.getCount
		/// </summary>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class response
		{

			/// <remarks/>
			public object[] Items;
		}
	}
}
