using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ClassLibraryVkontakteChecker.XmlData
{
	using System.Xml.Serialization;
	public class vkontakteError
	{
		//------------------------------------------------------------------------------
		// <auto-generated>
		//     Этот код создан программой.
		//     Исполняемая версия:4.0.30319.17379
		//
		//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
		//     повторной генерации кода.
		// </auto-generated>
		//------------------------------------------------------------------------------



		// 
		// Этот исходный код был создан с помощью xsd, версия=4.0.30319.1.
		// 


		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class error
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string error_code;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string error_msg;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "request_params" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public errorRequest_params[] request_params;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class errorRequest_params
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "param" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public errorRequest_paramsParam[] param;

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string list;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class errorRequest_paramsParam
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string key;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string value;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class NewDataSet
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "error" )]
			public error[] Items;
		}

	}

}