//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17379
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.1.
// 

namespace ClassLibraryVkontakteChecker.XmlData
{

	public class wall_get
	{
		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class attachment
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string type;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "link" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public attachmentLink[] link;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "photo" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public attachmentPhoto[] photo;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class attachmentLink
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string url;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string title;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string description;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class attachmentPhoto
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string pid;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string aid;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string owner_id;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string user_id;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string src;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string src_big;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string src_small;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string text;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string created;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string access_key;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class response
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string count;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "post" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePost[] post;

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string list;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePost
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string id;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string from_id;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string to_id;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string date;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string text;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string online;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string reply_count;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "media" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostMedia[] media;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "attachment" )]
			public attachment[] attachment;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "attachments" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostAttachments[] attachments;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "comments" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostComments[] comments;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "likes" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostLikes[] likes;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "reposts" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostReposts[] reposts;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "post_source" , Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public responsePostPost_source[] post_source;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostMedia
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string type;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string share_url;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string share_title;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostAttachments
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "attachment" )]
			public attachment[] attachment;

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string list;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostComments
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string count;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string can_post;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostLikes
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string count;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string user_likes;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string can_like;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string can_publish;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostReposts
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string count;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string user_reposted;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		public partial class responsePostPost_source
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( Form = System.Xml.Schema.XmlSchemaForm.Unqualified )]
			public string type;
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "4.0.30319.1" )]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute( "code" )]
		[System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true )]
		[System.Xml.Serialization.XmlRootAttribute( Namespace = "" , IsNullable = false )]
		public partial class NewDataSet
		{

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute( "attachment" , typeof( attachment ) )]
			[System.Xml.Serialization.XmlElementAttribute( "response" , typeof( response ) )]
			public object[] Items;
		}
	}
}